from enum import Enum


class KnowledgeType(str, Enum):
    FACT = "FACT"
    PRINCIPLE = "PRINCIPLE"
    DECISION_RULE = "DECISION_RULE"
    HEURISTIC = "HEURISTIC"
    EXCEPTION = "EXCEPTION"
    FAILURE_LESSON = "FAILURE_LESSON"
    TRADE_OFF = "TRADE_OFF"
    EXPERT_OPINION = "EXPERT_OPINION"


class GapDimension(str, Enum):
    WHAT = "WHAT"
    WHY = "WHY"
    WHEN = "WHEN"
    HOW = "HOW"
    SIGNAL = "SIGNAL"
    EXCEPTION = "EXCEPTION"
    FAILURE = "FAILURE"
    TRADE_OFF = "TRADE_OFF"


class GapType(str, Enum):
    MISSING_KNOWLEDGE = "MISSING_KNOWLEDGE"
    SHALLOW_KNOWLEDGE = "SHALLOW_KNOWLEDGE"
    MISSING_CONTEXT = "MISSING_CONTEXT"
    MISSING_SIGNAL = "MISSING_SIGNAL"
    MISSING_EXCEPTION = "MISSING_EXCEPTION"
    MISSING_FAILURE = "MISSING_FAILURE"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    CONFLICT = "CONFLICT"


class ConflictType(str, Enum):
    WORDING_DIFFERENCE = "WORDING_DIFFERENCE"
    CONTEXT_DIFFERENCE = "CONTEXT_DIFFERENCE"
    CONDITIONAL_CONFLICT = "CONDITIONAL_CONFLICT"
    DIRECT_CONFLICT = "DIRECT_CONFLICT"


class ConflictSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ValidationStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    CANDIDATE = "CANDIDATE"
    VALIDATING = "VALIDATING"
    VERIFIED = "VERIFIED"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    EXPERT_OPINION = "EXPERT_OPINION"
    REJECTED = "REJECTED"


class QuestionType(str, Enum):
    DEPTH = "DEPTH"
    EXCEPTION = "EXCEPTION"
    FAILURE = "FAILURE"
    EVIDENCE = "EVIDENCE"
    CONFLICT_RESOLUTION = "CONFLICT_RESOLUTION"
    TRADE_OFF = "TRADE_OFF"
    CONTEXT = "CONTEXT"


class RelationType(str, Enum):
    SUPPORTS = "SUPPORTS"
    REFINES = "REFINES"
    HAS_EXCEPTION = "HAS_EXCEPTION"
    CONTRADICTS = "CONTRADICTS"
    CONTEXT_DIFFERS = "CONTEXT_DIFFERS"
    SUPERSEDES = "SUPERSEDES"
    UNRELATED = "UNRELATED"


class RelationTargetType(str, Enum):
    KNOWLEDGE = "KNOWLEDGE"
    EVIDENCE = "EVIDENCE"


class SynthesisOperation(str, Enum):
    ENRICH = "ENRICH"
    ADD_EXCEPTION = "ADD_EXCEPTION"
    SPLIT_BY_CONTEXT = "SPLIT_BY_CONTEXT"
    MERGE = "MERGE"
    SUPERSEDE = "SUPERSEDE"
    KEEP_CONFLICT = "KEEP_CONFLICT"


class HumanReviewAction(str, Enum):
    ACCEPT = "ACCEPT"
    EDIT = "EDIT"
    REJECT = "REJECT"